language : python

version :
  - 3.6

service :
  - postgresql
 
install:
  - pip install -r requirements.txt

before_script:
 - psql -c "CREATE DATABASE testdb;" -U postgres
#  - psql -c "CREATE DATABASE epicmail;" -U postgres


script:
  - pytest --cov

after_script:
  - coveralls