language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS = test_env

install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database epicmail'
  - . .testing

script:
  - python3 -m pytest --cov=app/

after_success:
  - coveralls