# language : python

# version :
#   - 3.6

# service :
#   - postgresql
 
# install:
#   - pip install -r requirements.txt

# before_script:
#  - psql -c "CREATE DATABASE testdb;" -U postgres
# #  - psql -c "CREATE DATABASE epicmail;" -U postgres


# script:
#   - pytest --cov

# after_script:
#   - coveralls

``` language: python
python:
 - "3.6.6"
services:
 - postgresql
env:
 global:
   - DB_NAME='testdb'
# command to install dependencies
install:
 - pip install -r requirements.txt
before_script:
 - "psql -c 'create database testdb;' -U postgres"
# command to run tests
script:
 - nosetests --with-coverage --cover-tests
 - coverage report

after_success:
 - coveralls

notifications:
 email: false